### ISSUE TITLE
modifier transforms don't appear to work

### ISSUE THREAD

**Issue by BryanCrotaz** [lifeart/ember-ref-bucket#11]
Ember 3.22
`{{create-tracked-ref "my-element"}}`
`Error: Compile Error: Unexpected Modifier create-tracked-ref @ 0..0`

`{{create-ref "my-element" bucket=this tracked=true}}` works

**Comment by lifeart** [comment]
@BryanCrotaz could you check adding addon to `dependencies`?

**Comment by lifeart** [comment]
can't reproduce, it may be an typo, added few more checks, including typo check  - https://github.com/lifeart/ember-ref-bucket/pull/13
