### ISSUE TITLE
It breaks when using options for `{{create-tracked-ref}}`

### ISSUE THREAD

**Issue by wozny1989** [lifeart/ember-ref-bucket#52]
When I try to use:
```hbs
<div {{create-tracked-ref "foo" attributes=true}}>Polars</div>
```
Throw error:
<img width="672" alt="image" src="https://github.com/lifeart/ember-ref-bucket/assets/36460224/061b0a04-d95f-4342-96b1-cb9366c229ac">

**Comment by lifeart** [comment]
`5.0.2` published

**Comment by wozny1989** [comment]
It was fast, thanks @lifeart !
